### ISSUE TITLE
Hovering over Health / Nano / Xp bar doesn't show current/max values

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#444]
**Describe the bug**
When hovering over the health / nano / xp bars, you don't see the hover popup with current & maximum values

**To Reproduce**
Hover over the bars

**Expected behavior**
Should show current / max value

**Screenshots**
(example current AO)
![image](https://github.com/project-rubika/issues/assets/156527345/65462f7e-a2cf-4a21-9072-5652791bceb6)

----

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Health, nano, and XP bars are missing the mouseover value displays that appear in the live game.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/30bf3d93-8703-425d-9493-0b659bf1afa9)
![image](https://github.com/user-attachments/assets/00a9e69b-1251-4c99-911d-3e8e286ce494)
![image](https://github.com/user-attachments/assets/c296a3d2-2a52-4534-aa94-70b4cb69e736)

This appears to now be solved. Closing as fixed as of 18/08/24.

**Comment by prkdrake** [comment]
Definitely still an issue. Caused by some update packet throwing things off - can reproduce generally by losing some health then healing, and hovering over your HP. Haven’t looked into it yet.

**Comment by Starbouy138** [comment]
Mine show XP but not health and nano at this moment in Borealis, after /camp relog it does show xp/health/nano values on hover.

**Comment by Dezzyx** [comment]
Shows for me

**Comment by RaggyLP** [comment]
After doing some further research on this, it appear that the issue becomes present when the value bars are outside of the clients 'old' resolution options, so if you are playing on resolutions that are native to the client before any .dll tweaks for modern resolutions, it is fine. 

Please see the attached images regarding this.

![areas psd(1)](https://github.com/user-attachments/assets/9a1e9874-0ac3-4ef2-887f-be316e9dbf1c)

![areas psd(2)](https://github.com/user-attachments/assets/e955b98a-0285-4857-a0a0-ce38b7d86a44)

As this is an issue that is inherent to the client, I'll mark this issue as closed.

**Comment by prkdrake** [comment]
I don't think that's quite right - I almost always play in a 1024x768 window when testing stuff locally for PRK and I notice this issue still, all the time

**Comment by RaggyLP** [comment]
Further research and discussion has shown that his is a result of the 'DailyLoginReward' window.

![image](https://github.com/user-attachments/assets/b875e918-2c9c-4fce-8237-dfb602f76032)

Setting it to false removes the deadzone on the window and on new character generation.
